apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charging_station_app.fullname" . }}-init-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.config.postgres.initConfig.POSTGRES_USER   }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.ROOT_PASSWORD   }}
  POSTGRES_DB: {{ .Values.config.postgres.initConfig.POSTGRES_DB   }}
  APP_DB_USER: {{ .Values.config.postgres.initConfig.APP_DB_USER   }}
  APP_DB_PASSWORD: {{ .Values.secret.postgres.DB_PASSWORD   }}
  APP_SCHEMA: {{ .Values.config.postgres.initConfig.APP_SCHEMA   }}