apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
labels:
  app: {{ include "postgres.name" . }}
data:
  POSTGRES_USER: {{ .Values.config.postgres.DB_USER | quote }}
  POSTGRES_DB: {{ .Values.config.postgres.DB_NAME | quote }}
  POSTGRES_PORT: {{ .Values.config.postgres.DB_PORT | quote }}