apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: {{ include "postgres.name" . }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ include "postgres.name" . }}
  type: ClusterIP