global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'   
  group_by: ['alertname']        
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - match:
        group: http_alerts       
      receiver: 'http-alerts-receiver'
      group_by: ['alertname', 'app']  

receivers:
  - name: 'default-receiver'
  - name: 'http-alerts-receiver'
