services:
  charging_station_app:
    image: charging-station-app:0.1.0
    env_file:
      - .app.env
    ports:
      - 8000:8000
    depends_on: 
      - db_init
      - redis
    command: ["--bind", "0.0.0.0:8000"]
    user: "1001:1001"
  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - ./.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .redis.env
    ports:
      - "6379:6379"
    volumes:
      - ./entrypoint/redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
    entrypoint: ["/usr/local/bin/redis-entrypoint.sh"]
    restart: always
    user: "redis:redis"
  db_init:
    image: postgres:15
    depends_on:
      - postgres_db
    env_file:
      - ./.db-init.env
    entrypoint: [ "bash", "/init-db.sh" ]
    volumes:
      - ./entrypoint/init-db.sh:/init-db.sh
volumes:
  pgdata:
