services:
  charging_station_app:
    image: charging-station-app:latest
    env_file:
      - .app.env
    ports:
      - 8000:8000
    depends_on: 
      - db_init
    command: ["--bind", "0.0.0.0:8000"]
  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - ./.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_init:
    image: postgres:15
    depends_on:
      - postgres_db
    env_file:
      - ./.db-init.env
    entrypoint: [ "bash", "/init-db.sh" ]
    volumes:
      - ./init-db.sh:/init-db.sh
volumes:
  pgdata:
