services:
  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - ./.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_init:
    image: postgres:15
    depends_on:
      - postgres_db
    env_file:
      - ./.db-init.env
    entrypoint: [ "bash", "/init-db.sh" ]
    volumes:
      - ./init-db.sh:/init-db.sh
volumes:
  pgdata:
