- name: Validate and initialize inputs
  import_tasks: validate_common.yml
  vars:
    vars_to_validate:
      - github_repo_url
      - github_personal_access_token
      - github_runner_name
      - github_runner_labels
      - kubectl_version
    variables_to_set:
      - var_name: github_runner_user
        var_value: "{{ github_runner_user_name | default(github_runner_user_default_name, true) }}"
      - var_name: github_runner_group
        var_value: "{{ github_runner_group_name | default(github_runner_group_default_name, true) }}"
      - var_name: github_runner_home_dir
        var_value: "/home/{{ github_runner_user | default(github_runner_user_name | default(github_runner_user_default_name, true), true) }}"

- name: Validate 'github_runner_release_url' is defined and valid URL
  ansible.builtin.assert:
    that:
      - github_runner_release_url is defined
      - github_runner_release_url | length > 0
      - github_runner_release_url is match("^(https)://[^\s/$.?#].[^\s]*$")
    fail_msg: "'github_runner_release_url' must be defined and be a valid HTTPS URL."

- name: Extract filename from URL
  ansible.builtin.set_fact:
    github_runner_filename: "{{ github_runner_release_url.split('/')[-1] }}"



- name: Set Kubernetes repo info based on OS family
  ansible.builtin.set_fact:
    kubernetes_repo:
      url: >-
        {% if ansible_os_family == 'Debian' %}
        https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/deb/
        {% elif ansible_os_family == 'RedHat' %}
        https://pkgs.k8s.io/core:/stable:/v{{ kubectl_version }}/rpm/
        {% else %}
        ""
        {% endif %}
      prefix: >-
        {% if ansible_os_family == 'Debian' %}
        deb
        {% elif ansible_os_family == 'RedHat' %}
        rpm
        {% else %}
        ""
        {% endif %}


- name: Fail if OS family not supported
  ansible.builtin.fail:
    msg: "Unsupported OS family {{ ansible_os_family }} para Kubernetes repo setup"
  when: kubernetes_repo.url is not defined or kubernetes_repo.url == ""


- name: Show default user for runner
  ansible.builtin.debug:
    msg: "User name: {{ github_runner_user }}"

- name: Show file name obtained from github runner url
  ansible.builtin.debug:
    msg: "User name: {{ github_runner_filename }}"

- name: Show default group for runner
  ansible.builtin.debug:
    msg: "Group name: {{ github_runner_group }}"
