apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
labels:
  app: {{ include "redis.name" . }}
data:
  REDIS_HOST: {{ .Values.config.redis.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.redis.REDIS_PORT | quote }}