replicaCount: 1

image:
  repository: postgres
  tag: 15
  pullPolicy: IfNotPresent

persistence:
  size: 4Gi
  storageClass: standard

config:
  postgres:
    DB_USER: postgres
    DB_PORT: "5432"
    DB_NAME: core

secret:
  postgres:
    DB_PASSWORD: mOV0HqXNAWkFhpOe