{
 "title": "FastAPI Dashboards",
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "label_values(up, app)" },
   { "name": "environment", "label": "Environment", "query": "label_values(up, environment)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=~\"$app\", environment=~\"$environment\"}[$__range])) by (endpoint, method)"
    }
   ]
  },
  {
   "title": "Percentiles per endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "\nhistogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=~\"$app\", environment=~\"$environment\"}[5m])) by (le, endpoint, method))\n",
     "legendFormat": "{{endpoint}} - {{method}} - p50"
    },
    {
     "expr": "\nhistogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{app=~\"$app\", environment=~\"$environment\"}[5m])) by (le, endpoint, method))\n",
     "legendFormat": "{{endpoint}} - {{method}} - p90"
    },
    {
     "expr": "\nhistogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=~\"$app\", environment=~\"$environment\"}[5m])) by (le, endpoint, method))\n",
     "legendFormat": "{{endpoint}} - {{method}} - p99"
    }
   ]
  },
  {
   "title": "Requests per error code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app=~\"$app\", environment=~\"$environment\", http_status=~\"4..|5..\"}[5m])) by (http_status)"
    }
   ]
  },
  {
   "title": "Top 10 Endpoints with errors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_requests_total{app=~\"$app\", environment=~\"$environment\", http_status=~\"4..|5..\"}[5m])) by (endpoint, http_status))",
     "legendFormat": "{{endpoint}} - {{http_status}}"
    }
   ]
  }
 ]
}