name: Build app image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for Docker image (optional)'
        required: false
        default: 'latest'
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/charging-station-app 

jobs:
  build-and-push:
    runs-on: [self-hosted, my-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image version
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [ "${{ github.ref_type }}" == "tag" ]; then
            echo "VERSION=${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:${VERSION} ./docker
          docker tag $IMAGE_NAME:${VERSION} $IMAGE_NAME:${GITHUB_SHA}

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${VERSION}
          docker push $IMAGE_NAME:${GITHUB_SHA}