name: Build app image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for Docker image (optional)'
        required: false
        default: 'latest'
  #push:
    #branches:
     # - main
    #tags:
     # - '[0-9]+.[0-9]+.[0-9]+'


jobs:
  build-and-push:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./python-app/charging_station_app    
          file: ./python-app/charging_station_app/docker/Dockerfile 
          push: true
          tags: |
            ${{ vars.DOCKER_REPO }}:${{ github.event.inputs.version }}
            ${{ vars.DOCKER_REPO }}:${{ github.sha }}
